FROM {{image}}

MAINTAINER Huy Doan

# Install Python
RUN yum install -y epel-release && yum install -y python-devel python-virtualenv gcc

# Install Ansible
RUN mkdir /opt/ansible && virtualenv /opt/ansible/venv && /opt/ansible/venv/bin/pip install ansible

ADD . /build
COPY .ansible-test /build
WORKDIR /build

CMD /opt/ansible/venv/bin/ansible-playbook -i inventory.yml \
    -c local -s -e testing=true -e role=$DOCKER_TEST_ROLE \
    {{ extra_args| join(" ") }} playbook.yml; /bin/bash
